title: "Reactors.IO"
name: Reactors.IO Website
description: Docs and resources for Reactors.IO
url: http://reactors.io
baseUrl: http://reactors.io
relative_permalinks: false
reactive_collections_version: 0.5
reactive_collections_snapshot_version: 0.6-SNAPSHOT
